library(ggplot2)
vgc <- read.csv("D:/system/VGC/vgc.csv", stringsAsFactors=FALSE)
p <- ggplot(data=vgc,aes(x=Duration.hour.,y=On.site.Charge,colour=Is.Integrity))
p + geom_point(aes(shape=Is.Integrity),size=4)
vgc_cheat <- subset(x = vgc,Is.Integrity=="no")
p + geom_point(aes(shape=Is.Integrity),size=4,position = "jitter")
last_plot()+scale_y_continuous(limits=c(-90,850))
last_plot()+geom_text(data=vgc_cheat,aes(x=Duration.hour.,y=On.site.Charge,label=Car.Dealer,hjust=0,vjust=1,angle=-32),position = "jitter")
last_plot()+theme(axis.text.x=element_text(size=20),axis.title.x=element_text(size=20))
last_plot()+theme(axis.text.y=element_text(size=20),axis.title.y=element_text(size=20))
last_plot()+theme(legend.text=element_text(size=20),legend.title=element_text(size=20),legend.position=c(0,0))
last_plot()+theme(plot.title=element_text(size=20))
p_h <- ggplot(data=vgc,aes(x=Duration.hour.))
p_h + geom_histogram(aes(fill=Is.Integrity),binwidth=0.05)+facet_grid(Is.Integrity~.)